Bison     854485755  8  6 f   -     -     -          135    0    0 
Bison     854485817  7  6 f   -     -     -          135    0    0 
Bison     854485843  7  6 f   -     -     -          135    0    0 
Bison     854485892  5  3 f   -     -     -          135    0    0 
Bison     854485929  5  3 f   -     -     -          135    0    0 
Bison     854486009  5  2 Bf  -     -     -          135   10    0 
Bison     854486047  5  1 Bf  -     -     -          125    5    0 
Bison     854486102  5  5 c   f     -     -          120   10    0 
Bison     854486119  5  4 c   c     k     k          110   20    0 9s 8c
Bison     854486184  4  2 r   r     -     -           90   40   70 
Bison     854486306  3  1 B   -     -     -          120   10   10 
Bison     854486314  3  1 Bc  b     kc    kc         120   60    0 Jh 8s
Bison     854486368  4  4 f   -     -     -           60    0    0 
Bison     854486390  4  3 f   -     -     -           60    0    0 
Bison     854486410  4  2 Br  b     -     -           60   30   55 
Bison     854486427  4  1 Bf  -     -     -           85    5    0 
Bison     854486440  3  3 rr  k     b     bA          80   80    0 5h 4d
Bison     854486507  3  3 rc  c     c     k         1000   60    0 4d 4s
Bison     854486556  4  2 Bk  k     k     k          940   10   18 5d 9d
Bison     854486681  4  1 Bc  k     kf    -          948   10    0 
Bison     854486764  3  3 r   bQ    -     -          938   30   60 
